### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by BartoszKacperski** [adinef/backBook#1]
@adinef In authentication controller you have forgotten to check a case when tokenService throws exception.

**Comment by adinef** [comment]
Thanks for contribution :+1:  The exception that is thrown is currently mapped with @ResponseStatus(code = HttpStatus.UNAUTHORIZED) annotation. I'll be moving this association to RestResponseExceptionHandler, Component annotated as @ControllerAdvice, under the net.fp.backBook.configuration package.

**Comment by BartoszKacperski** [comment]
But the exception is catched in try-catch block and you return ResponseEntity in this method

**Comment by adinef** [comment]
You're absolutely right. I forgot to rework it after exception mapping, it is done now. Please consider looking at AuthorizationController in net.fp.backBook.controllers and share your thoughts.

**Comment by BartoszKacperski** [comment]
It's better but not perfect. Code coverage is still not 100%, because you don't put login and password in Credential builder and you use anyString matcher which doesn't catch this case.

**Comment by adinef** [comment]
Ok, thanks, closing the issue now :)
